apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-events-ingress
  namespace: user-events-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /api/v1/user-events(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: user-events-service
                port:
                  number: 3000